version: '3.9'

services:
  app: &app
    build: 
      context: .
    container_name: app
    tty: true
    networks:
      - rabbitmq_network
    environment:
      - RUBY_YJIT_ENABLE=1
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    depends_on:
      - rabbitmq
    entrypoint: ./entrypoint.sh

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.12-management"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - rabbitmq_network
    ports: 
      - "15672:15672"
      - "5672:5672"

  ngrok:
    image: ngrok/ngrok:alpine
    container_name: ngrok
    command: http --domain=caring-flea-leading.ngrok-free.app http://app:5000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    networks:
      - rabbitmq_network

volumes:
  rubygems:
  rabbitmq-data:

networks:
  rabbitmq_network:
    name: rabbitmq_network
    external: true
