version: '3.9'

services:
  app: &app
    build: 
      context: .
    container_name: app
    tty: true
    networks:
      - rabbitmq_network
    environment:
      - RUBY_YJIT_ENABLE=1
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    depends_on:
      - rabbitmq
    entrypoint: ./entrypoint.sh
 

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.12-management"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - rabbitmq_network
    ports: 
      - "15672:15672"
      - "5672:5672"
    
volumes:
  rubygems:
  rabbitmq-data:


networks:
  default:
  rabbitmq_network:
    name: rabbitmq_network
    external: true