version: '3.9'

services:
  webapp:
    build: 
      context: .
    container_name: webapp
    networks:
      - rabbitmq_network
    tty: true
    environment:
      - RUBY_YJIT_ENABLE=1
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    entrypoint: ./entrypoint.sh
 
    
volumes:
  rubygems:


networks:
  default:
  rabbitmq_network:
    name: rabbitmq_network
    external: true